import { Registro } from './types';

export const mockRegistros: Registro[] = [
  {
    id: 8,
    codigo: '8',
    fecha_recepcion: '2026-06-23',
    titulo_referencia: 'INVENTARIO DE LA PARROQUIA DE RIO CUARTO Y DEM S CAPILLAS: LA ESQUINA, LA CARLOTA, REDUCCION Y NUESTRA SEÑORA DE LA MERCED DE ACHIRAS',
    descripcion_breve: 'Inventario general de bienes y documentos de la parroquia de Río Cuarto y sus capillas sufragáneas. Incluye registro de ornamentos, vasos sagrados y libros parroquiales.',
    origen: 'Parroquia de Río Cuarto',
    categoria: 'Inventario',
    anio: 1838,
    numero_protocolar: 'RC-1838-001',
    segmento: 'Histórico',
    tema: 'Inventario parroquial',
    area: 'Archivo diocesano',
    asunto: 'Inventario de bienes y documentos',
    iniciador: 'Pbro. Juan de Dios Rivero',
    destinatarios: 'Obispado de Córdoba',
    grupo: 'Parroquias',
    serie: 'Inventarios',
    sub_serie: 'Inventarios de bienes',
    soporte: 'Papel',
    estado_conservacion: 'Bueno',
    cond_acceso: 'Libre',
    cond_reproduccion: 'Permitida',
    lengua_escritura: 'Español',
    original_copia: 'Original',
    lugar_destino: 'Archivo Histórico Diocesano',
    ubicacion_sala: 'Archivo Histórico',
    pasillo: 'A',
    estanteria: '3',
    casillero: '12',
    caja_nro: '47',
    legajo: '2',
    numero: '8',
    folios: '24',
    hojas: '48',
    medidas: '22',
    nota_archivero: 'Documento en buen estado. Algunas páginas con manchas de humedad en los márgenes.',
    visibilidad: 'publico',
    archivos: [{ id: 1, nombre: 'inventario_1838.png', tipo: 'PNG', url: '#' }],
    created_at: '2026-06-23T10:00:00Z',
  },
  {
    id: 6,
    codigo: '6',
    fecha_recepcion: '2026-06-22',
    titulo_referencia: 'LIBRO DE BAUTISMOS DE LA PARROQUIA NUESTRA SEÑORA DE LA MERCED - TOMO III',
    descripcion_breve: 'Registro de bautismos celebrados entre 1872 y 1889 en la Parroquia Nuestra Señora de la Merced. Contiene 847 actas con nombres, fechas y padrinos.',
    origen: 'Parroquia Nuestra Señora de la Merced',
    categoria: 'Registro sacramental',
    anio: 1872,
    numero_protocolar: 'NM-1872-T03',
    segmento: 'Sacramental',
    tema: 'Bautismos',
    area: 'Sacramentos',
    asunto: 'Registro de bautismos 1872-1889',
    iniciador: 'Pbro. Carlos Montes',
    destinatarios: 'Archivo Diocesano',
    grupo: 'Registros sacramentales',
    serie: 'Bautismos',
    sub_serie: 'Libros de bautismos',
    soporte: 'Pergamino encuadernado',
    estado_conservacion: 'Excelente',
    cond_acceso: 'Restringido',
    cond_reproduccion: 'Bajo solicitud',
    lengua_escritura: 'Español / Latín',
    original_copia: 'Original',
    lugar_destino: 'Archivo Histórico Diocesano',
    ubicacion_sala: 'Archivo Histórico',
    pasillo: 'B',
    estanteria: '1',
    casillero: '4',
    caja_nro: '12',
    legajo: '3',
    numero: '6',
    folios: '186',
    hojas: '372',
    medidas: '25',
    nota_archivero: 'Encuadernación original en buen estado. Tapa con deterioro leve.',
    visibilidad: 'publico',
    archivos: [
      { id: 2, nombre: 'bautismos_t3_p1.png', tipo: 'PNG', url: '#' },
      { id: 3, nombre: 'bautismos_t3_catalogo.pdf', tipo: 'PDF', url: '#' },
    ],
    created_at: '2026-06-22T09:30:00Z',
  },
  {
    id: 2,
    codigo: '2',
    fecha_recepcion: '2026-06-19',
    titulo_referencia: 'ACTAS CAPITULARES DEL CABILDO ECLESIÁSTICO - 1901 A 1915',
    descripcion_breve: 'Colección de actas de las reuniones del Cabildo Eclesiástico de la Diocesano. Período de gran actividad pastoral y reorganización institucional.',
    origen: 'Cabildo Eclesiástico',
    categoria: 'Actas',
    anio: 1901,
    numero_protocolar: 'CAP-1901-001',
    segmento: 'Administrativo',
    tema: 'Gobierno eclesiástico',
    area: 'Cabildo',
    asunto: 'Actas capitulares 1901-1915',
    iniciador: 'Cancillería Diocesana',
    destinatarios: 'Archivo Central',
    grupo: 'Gobierno',
    serie: 'Actas capitulares',
    sub_serie: '',
    soporte: 'Papel',
    estado_conservacion: 'Regular',
    cond_acceso: 'Investigadores',
    cond_reproduccion: 'Permitida con autorización',
    lengua_escritura: 'Español',
    original_copia: 'Original',
    lugar_destino: 'Archivo Histórico Diocesano',
    ubicacion_sala: 'Archivo Histórico',
    pasillo: 'C',
    estanteria: '2',
    casillero: '8',
    caja_nro: '23',
    legajo: '1',
    numero: '2',
    folios: '312',
    hojas: '624',
    medidas: '22',
    nota_archivero: 'Algunas actas con firma deteriorada. Buen estado general.',
    visibilidad: 'publico',
    archivos: [{ id: 4, nombre: 'actas_capitulares.pdf', tipo: 'PDF', url: '#' }],
    created_at: '2026-06-19T14:00:00Z',
  },
  {
    id: 3,
    codigo: '3',
    fecha_recepcion: '2026-06-19',
    titulo_referencia: 'CORRESPONDENCIA EPISCOPAL - OBISPO FRAY MARCELINO DE LA PAZ (1856-1872)',
    descripcion_breve: 'Conjunto de cartas pastorales, circulares y correspondencia del obispo Fray Marcelino de la Paz durante su ministerio episcopal. Incluye comunicaciones con el Vaticano.',
    origen: 'Secretaría Episcopal',
    categoria: 'Correspondencia',
    anio: 1856,
    numero_protocolar: 'EP-1856-CP',
    segmento: 'Episcopal',
    tema: 'Correspondencia oficial',
    area: 'Obispado',
    asunto: 'Cartas y circulares episcopales',
    iniciador: 'Obispo Fray Marcelino de la Paz',
    destinatarios: 'Varios / Santa Sede',
    grupo: 'Correspondencia',
    serie: 'Correspondencia episcopal',
    sub_serie: 'Cartas pastorales',
    soporte: 'Papel verjurado',
    estado_conservacion: 'Bueno',
    cond_acceso: 'Investigadores',
    cond_reproduccion: 'Bajo solicitud',
    lengua_escritura: 'Español / Latín / Italiano',
    original_copia: 'Original',
    lugar_destino: 'Archivo Histórico Diocesano',
    ubicacion_sala: 'Archivo Histórico',
    pasillo: 'A',
    estanteria: '5',
    casillero: '2',
    caja_nro: '8',
    legajo: '4',
    numero: '3',
    folios: '89',
    hojas: '178',
    medidas: '21',
    nota_archivero: 'Conjunto excepcional. Algunas cartas con sellos episcopales intactos.',
    visibilidad: 'publico',
    archivos: [{ id: 5, nombre: 'correspondencia_1856.png', tipo: 'PNG', url: '#' }],
    created_at: '2026-06-19T16:00:00Z',
  },
  {
    id: 1,
    codigo: '1',
    fecha_recepcion: '2026-06-19',
    titulo_referencia: 'LIBRO DE MATRIMONIOS - PARROQUIA SAN PEDRO APÓSTOL (1823-1850)',
    descripcion_breve: 'Registro de matrimonios canónicos celebrados en la Parroquia San Pedro Apóstol durante el período 1823-1850.',
    origen: 'Parroquia San Pedro Apóstol',
    categoria: 'Registro sacramental',
    anio: 1823,
    numero_protocolar: 'SP-1823-M01',
    segmento: 'Sacramental',
    tema: 'Matrimonios',
    area: 'Sacramentos',
    asunto: 'Libro de matrimonios 1823-1850',
    iniciador: 'Pbro. Anastasio Pereyra',
    destinatarios: 'Archivo Diocesano',
    grupo: 'Registros sacramentales',
    serie: 'Matrimonios',
    sub_serie: 'Libros de matrimonios',
    soporte: 'Papel',
    estado_conservacion: 'Regular',
    cond_acceso: 'Investigadores',
    cond_reproduccion: 'Bajo solicitud',
    lengua_escritura: 'Español',
    original_copia: 'Original',
    lugar_destino: 'Archivo Histórico Diocesano',
    ubicacion_sala: 'Archivo Histórico',
    pasillo: 'B',
    estanteria: '2',
    casillero: '9',
    caja_nro: '5',
    legajo: '1',
    numero: '1',
    folios: '142',
    hojas: '284',
    medidas: '23',
    nota_archivero: 'Primeras páginas con manchas de humedad. Texto legible.',
    visibilidad: 'privado',
    archivos: [],
    created_at: '2026-06-19T08:00:00Z',
  },
  {
    id: 5,
    codigo: '5',
    fecha_recepcion: '2026-06-22',
    titulo_referencia: 'DECRETO DE DIOCESANO - COPIA NOTARIAL',
    descripcion_breve: 'Copia notarial del decreto pontificio de la Diocesano. Documento de carácter reservado.',
    origen: 'Santa Sede',
    categoria: 'Decreto',
    anio: 1934,
    numero_protocolar: 'SS-1934-DEC',
    segmento: 'Pontificio',
    tema: 'Diocesana',
    area: 'Cancillería',
    asunto: 'Decreto de diocesano',
    iniciador: 'Santa Sede',
    destinatarios: 'Obispado',
    grupo: 'Documentos fundacionales',
    serie: 'Decretos',
    sub_serie: '',
    soporte: 'Pergamino',
    estado_conservacion: 'Excelente',
    cond_acceso: 'Restringido',
    cond_reproduccion: 'No permitida',
    lengua_escritura: 'Latín',
    original_copia: 'Copia',
    lugar_destino: 'Caja fuerte',
    ubicacion_sala: 'Archivo Reservado',
    pasillo: '',
    estanteria: '',
    casillero: '',
    caja_nro: '',
    legajo: '1',
    numero: '5',
    folios: '4',
    hojas: '8',
    medidas: '35',
    nota_archivero: 'Acceso solo con autorización del Sr. Obispo.',
    visibilidad: 'privado',
    archivos: [],
    created_at: '2026-06-22T11:00:00Z',
  },
];

export const getPublicRegistros = () => mockRegistros.filter((r) => r.visibilidad === 'publico');
export const getAllRegistros = () => mockRegistros;
export const getRegistroById = (id: number) => mockRegistros.find((r) => r.id === id);
